{% set version = '1.26.38' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-copynumber
  version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/BrunoGrandePhD/copynumber
  git_tag: v1.26.38

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}filesystem        # [win]
    - {{posix}}git
    - {{posix}}zip               # [win]

  host:
    - r-base
    - bioconductor-biocgenerics
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors

  run:
    - r-base
    - bioconductor-biocgenerics
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('copynumber')"           # [not win]
    - "\"%R%\" -e \"library('copynumber')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/BrunoGrandePhD/copynumber
  license: Artistic-2.0
  summary: Penalized least squares regression is applied to fit piecewise constant curves to
    copy number data to locate genomic regions of constant copy number. Procedures are
    available for individual segmentation of each sample, joint segmentation of several
    samples and joint segmentation of the two data tracks from SNP-arrays. Several plotting
    functions are available for visualization of the data and the segmentation results.
  license_family: OTHER
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0'

# The original CRAN metadata for this package was:

# Package: copynumber
# Title: Segmentation of single- and multi-track copy number data by penalized least squares regression
# Version: 1.26.38
# Author: Gro Nilsen, Knut Liestoel and Ole Christian Lingjaerde
# Maintainer: Gro Nilsen <gronilse@ifi.uio.no>
# Description: Penalized least squares regression is applied to fit piecewise constant curves to copy number data to locate genomic regions of constant copy number. Procedures are available for individual segmentation of each sample, joint segmentation of several samples and joint segmentation of the two data tracks from SNP-arrays. Several plotting functions are available for visualization of the data and the segmentation results.
# License: Artistic-2.0
# LazyData: yes
# Date: 2013-04-16
# BuildResaveData: best
# Depends: R (>= 3.5), BiocGenerics
# Imports: S4Vectors, IRanges, GenomicRanges
# biocViews: aCGH, SNP, CopyNumberVariation, Genetics, Visualization
# git_url: https://git.bioconductor.org/packages/copynumber
# git_branch: RELEASE_3_10
# git_last_commit: c3a9594
# git_last_commit_date: 2019-10-29
# Date/Publication: 2019-10-29
# NeedsCompilation: no
# Packaged: 2019-10-30 00:39:28 UTC; biocbuild

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
